name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get and install vagrant
      run: wget https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_x86_64.deb && sudo dpkg -i vagrant_2.2.19_x86_64.deb
    - name: Get and install virtualbox
      run: sudo apt-get install virtualbox virtualbox-guest-utils -y

    - name: Create hostonlyif
      run: vboxmanage hostonlyif create
    
    - name: Configure /etc/vbox/networks
      run: sudo mkdir /etc/vbox/ && sudo echo "* 192.168.56.0/24 192.168.99.0/24" > /etc/vbox/networks.conf
    
    - name: Configure hostonlyif
      run: vboxmanage hostonlyif ipconfig 'vboxnet0' --ip 192.168.99.1 --netmask 255.255.255.0

    - name: Cache Vagrant boxes
      uses: actions/cache@v3
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Show Vagrant version
      run: vagrant --version

    - name: Show VBox version
      run: vboxmanage --version

    - name: Run vagrant up
      run: vagrant up

    - name: ssh into box after boot
      run: vagrant ssh -c "echo 'hello world!'"